tkhq/frames

export/index.html, recovery/index.html
Pretty simple change: let's try/catch around events we're receiving / processing and "throw" errors via `postMessage`. Parent pages do not have the ability to catch errors within cross-domain iframes unfortunately.
As step (2) I'll listen for these events in our SDK and make sure to bubble them as errors by `reject`ing the promise so callers can chain (`injectBundle.then(...).catch(...)`)
=> Send `ERROR` event when something goes wrong in event processing logic

export/index.html
Display the mnemonic as just text. Minimize what CSS attributes are set for the mnemonic and key by removing border and padding. The text's font style itself cannot be changed so we are continuing to set those attributes.
Now it just looks like this, for example
=> Change  mnemonic display

export/index.html
Remove unnecessary font weight attribute, align text to left instead of center, and wrap around text (this breaks the private key text onto multiple lines as needed, thus preventing scrolling)
=> More styling changes

kustomize/resources.yaml
This pod doesn't need much, in production it only uses:
```
NAME                      CPU(cores)   MEMORY(bytes)
frames-55b57894cd-nksbh   0m           3Mi
```
=> kustomize: add resource request for memory

export/index.html, export/index.test.js
ES module [@noble/ed25519](https://www.npmjs.com/package/@noble/ed25519). Addresses https://github.com/tkhq/frames/pull/27#discussion_r1524004161
**Fast follow**: Inline and attribute code due to sensitive nature of this private key export functionality.
=> Use Ed25519 package for solana public keys

export/index.html
Need to import `sha512` for `ed.getPublicKey` and use sync instead of async method to get public key. Do not pass `publicKey` param to `onInjectKeyBundle` and remove the public key HTML elements used for testing.
=> Sha512 ESM

auth/index.html, auth/index.test.js, export/index.html, export/index.test.js
Pretty straightforward: this change adds some validation to the argument passed to `uint8arrayFromHexString` and errors explicitly if it's bad (not a string, or an empty string, or a non-hex string)
=> Harden `uint8arrayFromHexString`

export/index.html, import/index.html, import/standalone.html
Based on ToB findings. Reset iframe embedded key in export and import after decryption and encryption respectively
=> ENG-1443: Reset iframe embedded key

.github/workflows/ci.yml, export/index.html, export/index.test.js, import/index.html, import/index.test.js, import/standalone.html
Based on ToB findings. Pin the signer enclave's quorum public key to import and export sites and verify the signed public keys from the enclave. Once we've deployed a new release that returns the enclave quorum public key in the import and export bundles, we can implement the TODOs I've left for checking that those fields aren't null and can be compared to the pinned quorum public key -- this lets the client know when the pinned quorum public key should be rotated.
=> ENG-1446: Verify enclave sig in export/import

export/index.html, import/index.html, import/standalone.html
Addresses ToB findings from ENG-1447 and ENG-1497. Verify the enclave signature and compare that expected metadata (organization id and user id) to the metadata contained in the importBundle and exportBundle.
Part 1a: https://github.com/tkhq/sdk/pull/233
Part 1b:  https://github.com/tkhq/frames/pull/33
Part 1c: https://github.com/tkhq/go-sdk/pull/47
Part 2: https://github.com/tkhq/tkcli/pull/59
Part 3: https://github.com/tkhq/mono/pull/2806
=> Part 1b/3: Verifiable metadata

kustomize/resources.yaml
This will ensure that we are running across multiple availability zones and hosts
=> kustomize: add topology spread constaints

auth/index.html, auth/index.test.js
Some randomly generated credentials would not be large enough to fully occupy the expected length of 32 bytes. This is specifically to address an issue where a JWT token would have `d, x, or y` values that are too short. 
Here's a sample error message: 
```
The JWK's "x" member defines an octet string of length 31 bytes but should be 32
```
Sample webcrypto tests can be found here: https://chromium.googlesource.com/chromium/src/+/master/components/test/data/webcrypto/bad_ec_keys.json
Tested locally by: creating a credential that results in a buffer of length 31 for any of the `d, x, or y` components of the JWT, ensuring that the buffer is padded, and that ultimately the credential can be injected + used to stamp a payload.
https://github.com/user-attachments/assets/0f44f7da-3468-4ac5-b483- …
=> add optional target length

README.md, export/index.template.html, export/index.test.js
Add support for adding css to the export iframe
=> Apply Settings to export

auth/index.html, export/index.template.html, import/index.template.html, import/standalone.template.html
Tweak `crypto.subtle.verify` params per https://developer.mozilla.org/en-US/docs/Web/API/EcdsaParams
`namedCurve` parameter simply wasn't being used.
- ✅ tested locally
- tested by putting this in editor to verify types
- `type AlgorithmIdentifier = Algorithm | string;` https://github.com/microsoft/TypeScript/blob/700ee076e515db2ef49d8cf7e4dc4bf70679575c/src/lib/dom.generated.d.ts#L28707
=> tweak verify params

export/index.template.html, import/index.template.html, import/standalone.template.html
$title
For TOB. Note that Turnkey-produced bundles are now all versioned; therefore, the `undefined` codepath is extremely unlikely to be used.
=> remove unused codepaths for bundle versions

auth/index.html, export/index.template.html, import/index.template.html
$title
SDK counterpart: https://github.com/tkhq/sdk/pull/467
This mainly serves the case where there are concurrent, or serial, requests. Request IDs are used to disambiguate between multiple requests.
=> add request id to iframe requests

README.md
- create separate sections of readme for import, export, and email auth
=> docs: create separate sections of readme for import, export, and email auth

auth/index.html
linked to: https://github.com/tkhq/sdk/pull/535
=> Custom ttl for init embedded key

auth/index.html, export/index.template.html, import/index.template.html
$title
SDK counterpart: https://github.com/tkhq/sdk/pull/533
=> add getEmbeddedKey

auth/index.html
$title
Accompanying `tkhq/sdk` change: https://github.com/tkhq/sdk/pull/571
https://github.com/user-attachments/assets/ce6339aa-7d5c-476a-8a62-3e7562bd83a8
=> expose functions to refresh an embedded key

.github/workflows/ci.yml, oauth-origin/index.test.js, oauth-origin/oauth-origin.js, oauth-redirect/index.html, oauth-redirect/index.test.js, oauth-redirect/oauth-redirect.js
> [!NOTE]
> Description below was generated by gpt-5-high based off of the PR diff 
- Adds provider support and robustness to `oauth-origin` and `oauth-redirect`.
- Improves test coverage and CI to include `oauth-origin` and `oauth-redirect`.
- .github/workflows/ci.yml
- Include `oauth-origin` and `oauth-redirect` in the matrix.
- oauth-origin.js
- Add provider support beyond Google:
- Apple: builds `https://appleid.apple.com/auth/authorize` with `response_type=code id_token`, `response_mode=fragment`, normalizes `redirect_uri` (ensures trailing slash before query), includes `nonce`.
- Facebook: builds `https://www.facebook.com/v23.0/dialog/oauth` with PKCE (`code_challenge` and `code_challenge_method=S256`), `response_type=code`, `scope=openid`, optional `state`, and normalized …
=> OAuth origin/redirect: add Facebook + Apple support, robust param handling, and CI coverage
